# This rule is not used by the project multicluster-role-assignment itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full administrative permissions over rbac.open-cluster-management.io resources.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: multicluster-role-assignment
    app.kubernetes.io/managed-by: kustomize
  name: multiclusterroleassignment-admin-role
rules:
- apiGroups:
  - rbac.open-cluster-management.io
  resources:
  - multiclusterroleassignments
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.open-cluster-management.io
  resources:
  - multiclusterroleassignments/status
  verbs:
  - get
