apiVersion: rbac.open-cluster-management.io/v1alpha1
kind: MulticlusterRoleAssignment
metadata:
  name: test-multicluster-role-assignment-multiple-2
  namespace: open-cluster-management-global-set
spec:
  subject:
    kind: User
    name: test-user-multiple-2
    apiGroup: rbac.authorization.k8s.io
  roleAssignments:
  - name: admin-assignment-cluster-1
    clusterRole: admin
    clusterSelection:
      type: placements
      placements:
      - name: placement-cluster-01
        namespace: open-cluster-management-global-set
  - name: view-assignment-all-clusters
    clusterRole: view
    clusterSelection:
      type: placements
      placements:
      - name: placement-cluster-01-02-03
        namespace: open-cluster-management-global-set
  - name: edit-assignment-single-namespace
    clusterRole: edit
    targetNamespaces:
    - default
    clusterSelection:
      type: placements
      placements:
      - name: placement-cluster-02
        namespace: open-cluster-management-global-set
  - name: monitoring-assignment-multi-namespace-single-cluster
    clusterRole: system:mon
    targetNamespaces:
    - monitoring
    - observability
    clusterSelection:
      type: placements
      placements:
      - name: placement-cluster-03
        namespace: open-cluster-management-global-set
  - name: dev-assignment-single-namespace-multi-cluster
    clusterRole: edit
    targetNamespaces:
    - development
    clusterSelection:
      type: placements
      placements:
      - name: placement-cluster-01-02
        namespace: open-cluster-management-global-set
  - name: logging-assignment-multi-namespace-multi-cluster
    clusterRole: view
    targetNamespaces:
    - logging
    - kube-system
    clusterSelection:
      type: placements
      placements:
      - name: placement-cluster-01-02-03
        namespace: open-cluster-management-global-set