apiVersion: rbac.open-cluster-management.io/v1beta1
kind: MulticlusterRoleAssignment
metadata:
  name: test-multicluster-role-assignment-single-clusterrolebinding
  namespace: open-cluster-management-global-set
spec:
  subject:
    kind: User
    name: test-user-single-clusterrolebinding
    apiGroup: rbac.authorization.k8s.io
  roleAssignments:
  - name: test-role-assignment
    clusterRole: view
    clusterSelection:
      type: placements
      placements:
      - name: placement-cluster-01
        namespace: open-cluster-management-global-set
